//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesCompanyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public string Name { get; set; }
        public string Contact { get; set; }
        public string CompanyOwner { get; set; }
    
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
