//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesCompanyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.SalesHistories = new HashSet<SalesHistory>();
        }
    
        public int Id_Person { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Contact { get; set; }
    
        public virtual ICollection<SalesHistory> SalesHistories { get; set; }
    }
}
