//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesCompanyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        public int Id_Person { get; set; }
        public int Id_Vehicle { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
