//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesCompanyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.SalesHistories = new HashSet<SalesHistory>();
        }
    
        public int Id_Vehicle { get; set; }
        public string VehicleType { get; set; }
        public string EngineType { get; set; }
        public string Producer { get; set; }
        public int Id_Extras { get; set; }
        public System.DateTime YearOfProduction { get; set; }
        public string TransmissionType { get; set; }
        public string Colour { get; set; }
        public string CoupeType { get; set; }
        public Nullable<bool> Sold { get; set; }
        public string Model { get; set; }
    
        public virtual EngineType EngineType1 { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<SalesHistory> SalesHistories { get; set; }
        public virtual VehicleExtra VehicleExtra { get; set; }
        public virtual VehicleType VehicleType1 { get; set; }
    }
}
